- .github/workflows/npm-publish.yml
- nest-cli.json
- package.json
- src/index.ts
> chore: build npm package

- src/index.ts
> feat: export database module and prisma service

- src/index.ts
> feat: export metrics api module

- package-lock.json
- package.json
- src/health/health.controller.ts
- src/health/health.module.ts
- src/health/notification-check.service.ts
- src/health/prisma-check.service.ts
> feat: liveness and readiness

- src/user/commands/handlers/__tests__/set-username.spec.ts
- src/user/commands/handlers/__tests__/update-password.spec.ts
- src/user/commands/handlers/set-username.handler.ts
> chore: user command tests

- .env.test
- .github/workflows/ci.yml
- docker-compose-test.yml
- jest.setup.ts
- package-lock.json
- package.json
- src/__tests__/create-models.ts
- src/user/queries/handlers/__tests__/get-projects-by-user-id.spec.ts
- src/user/queries/handlers/__tests__/get-user-organization.spec.ts
- src/user/queries/handlers/__tests__/get-user.spec.ts
- src/user/queries/handlers/get-projects-by-user-id.handler.ts
- src/user/queries/handlers/get-user.handler.ts
> chore: user queries tests

- .env.test
- src/__tests__/create-models.ts
- src/draft/commands/handlers/__tests__/create-revision.spec.ts
- src/draft/commands/handlers/__tests__/utils.ts
> chore: CreateRevisionHandler

- src/features/draft/commands/handlers/__tests__/create-row.spec.ts
- src/features/draft/commands/handlers/__tests__/update-table.spec.ts
- src/features/draft/commands/handlers/__tests__/utils.ts
- src/features/share/schema/json-patch-schema.spec.ts
- src/features/share/schema/json-patch-schema.ts
- src/features/share/schema/meta-schema.ts
> chore: UpdateTableHandler

- src/features/draft/commands/handlers/__tests__/remove-row.spec.ts
- src/features/draft/commands/handlers/update-table.handler.ts
> chore: RemoveRowHandler

- src/features/draft/commands/handlers/__tests__/api-create-revision.spec.ts
- src/features/draft/commands/handlers/__tests__/api-create-row.spec.ts
- src/features/draft/commands/handlers/__tests__/api-create-table.spec.ts
- src/features/draft/commands/handlers/__tests__/api-remove-row.spec.ts
- src/features/draft/commands/handlers/__tests__/api-remove-table.spec.ts
- src/features/draft/commands/handlers/__tests__/api-revert-changes.spec.ts
- src/features/draft/commands/handlers/__tests__/api-update-row.spec.ts
- src/features/draft/commands/handlers/__tests__/api-update-table.spec.ts
- src/features/draft/commands/handlers/__tests__/utils.ts
- src/features/draft/commands/handlers/api-create-revision.handler.ts
- src/features/draft/commands/handlers/api-revert-changes.handler.ts
- src/features/draft/commands/impl/api-create-revision.command.ts
- src/features/draft/commands/impl/api-revert-changes.command.ts
- src/features/revision/queries/commands/get-revision.handler.ts
- src/features/revision/queries/impl/get-revision.query.ts
> chore: api draft commands

- src/features/project/commands/handlers/__tests__/create-project.handler.spec.ts
- src/features/project/commands/handlers/__tests__/utils.ts
- src/features/project/commands/handlers/create-project.handler.ts
- src/features/project/commands/impl/create-project.command.ts
> chore: CreateProjectHandler

- .github/workflows/build.yml
- package-lock.json
- package.json
- src/features/project/commands/handlers/__tests__/api-create-project.spec.ts
- src/features/project/commands/handlers/api-create-project.handler.ts
- src/features/project/commands/impl/api-create-project.command.ts
- src/features/project/queries/handlers/get-project-by-id.handler.ts
- src/features/project/queries/impl/get-project-by-id.query.ts
> chore: CreateProjectHandler, ApiCreateProjectHandler

- src/features/draft/commands/handlers/__tests__/create-row.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/create-schema.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/internal-create-row.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/internal-update-row.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/update-schema.spec.ts
- src/features/draft/commands/handlers/create-row.handler.ts
- src/features/draft/commands/handlers/create-table.handler.ts
- src/features/draft/commands/handlers/index.ts
- src/features/draft/commands/handlers/transactional/create-schema.handler.ts
- src/features/draft/commands/handlers/transactional/internal-create-row.handler.ts
- src/features/draft/commands/handlers/transactional/internal-update-row.handler.ts
- src/features/draft/commands/handlers/transactional/update-schema.handler.ts
- src/features/draft/commands/handlers/transactional/validate-data.handler.ts
- src/features/draft/commands/handlers/update-row.handler.ts
- src/features/draft/commands/handlers/update-table.handler.ts
- src/features/draft/commands/impl/api-create-row.command.ts
- src/features/draft/commands/impl/create-row.command.ts
- src/features/draft/commands/impl/transactional/create-schema.command.ts
- src/features/draft/commands/impl/transactional/internal-create-row.command.ts
- src/features/draft/commands/impl/transactional/internal-update-row.command.ts
- src/features/draft/commands/impl/transactional/update-schema.command.ts
- src/features/draft/commands/impl/transactional/validate-data.command.ts
- src/features/draft/draft.transactional.commands.ts
> refactor: schema row commands

- prisma/migrations/20250112193723_row_meta/migration.sql
- prisma/schema.prisma
- src/features/draft/commands/handlers/__tests__/create-table.handler.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/create-schema.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/internal-create-row.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/internal-update-row.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/update-rows.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/update-schema.spec.ts
- src/features/draft/commands/handlers/__tests__/update-table.spec.ts
- src/features/draft/commands/handlers/__tests__/utils.ts
- src/features/draft/commands/handlers/transactional/create-schema.handler.ts
- src/features/draft/commands/handlers/transactional/get-or-create-draft-row.handler.ts
- src/features/draft/commands/handlers/transactional/get-or-create-draft-rows.handler.ts
- src/features/draft/commands/handlers/transactional/internal-create-row.handler.ts
- src/features/draft/commands/handlers/transactional/internal-update-row.handler.ts
- src/features/draft/commands/handlers/transactional/update-schema.handler.ts
- src/features/draft/commands/handlers/update-table.handler.ts
- src/features/draft/commands/impl/transactional/internal-create-row.command.ts
- src/features/draft/commands/impl/transactional/internal-update-row.command.ts
- src/features/draft/commands/impl/transactional/update-schema.command.ts
- src/features/draft/json-schema-validator.service.ts
- src/features/share/queries/handlers/transactional/get-table-schema.handler.ts
- src/features/share/queries/impl/transactional/get-table-schema.query.ts
- src/features/share/schema/history-patches-schema.spec.ts
- src/features/share/schema/history-patches-schema.ts
- src/features/share/schema/json-patch-schema.spec.ts
- src/features/share/schema/json-patch-schema.ts
> feat: schema patches

- prisma/migrations/20250209123106_table_created_id/migration.sql
- prisma/schema.prisma
- src/features/draft/commands/handlers/__tests__/create-table.handler.spec.ts
- src/features/draft/commands/handlers/__tests__/remove-row.spec.ts
- src/features/draft/commands/handlers/__tests__/remove-table.spec.ts
- src/features/draft/commands/handlers/__tests__/update-table.spec.ts
- src/features/draft/commands/handlers/__tests__/utils.ts
- src/features/draft/commands/handlers/create-table.handler.ts
- src/features/draft/commands/handlers/transactional/get-or-create-draft-table.handler.ts
- src/features/draft/draft-context.service.ts
- src/features/draft/draft-request-dto/table-request.dto.ts
- src/features/project/commands/handlers/__tests__/utils.ts
- src/features/project/commands/handlers/create-project.handler.ts
- src/features/share/queries/handlers/transactional/find-table-in-revision-or-throw.handler.ts
- src/features/share/queries/types/find-table-in-revision.types.ts
> feat: table.createdId

- prisma/migrations/20250209195205_row_created_id/migration.sql
- prisma/schema.prisma
- src/features/draft/commands/handlers/__tests__/create-row.spec.ts
- src/features/draft/commands/handlers/__tests__/remove-row.spec.ts
- src/features/draft/commands/handlers/__tests__/remove-table.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/internal-create-row.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/internal-update-row.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/update-rows.spec.ts
- src/features/draft/commands/handlers/__tests__/update-row.spec.ts
- src/features/draft/commands/handlers/__tests__/utils.ts
- src/features/draft/commands/handlers/transactional/get-or-create-draft-row.handler.ts
- src/features/draft/commands/handlers/transactional/get-or-create-draft-rows.handler.ts
- src/features/draft/commands/handlers/transactional/internal-create-row.handler.ts
- src/features/draft/draft-context.service.ts
- src/features/draft/draft-request-dto/row-request.dto.ts
- src/features/row/queries/handlers/__tests__/transactional/find-row-in-table-or-throw.handler.spec.ts
- src/features/share/queries/handlers/transactional/find-row-in-table-or-throw.handler.ts
- src/features/share/queries/types/find-row-in-table.types.ts
> feat: row.created

- src/api/graphql-api/draft/draft.resolver.ts
- src/api/graphql-api/draft/input/index.ts
- src/api/graphql-api/draft/input/rename-row.input.ts
- src/api/graphql-api/draft/model/rename-row-result.model.ts
- src/api/rest-api/row/dto/index.ts
- src/api/rest-api/row/dto/rename-row.dto.ts
- src/api/rest-api/row/model/index.ts
- src/api/rest-api/row/model/rename-row.response.ts
- src/api/rest-api/row/row-by-id.controller.ts
- src/features/draft/commands/handlers/__tests__/api-rename-row.spec.ts
- src/features/draft/commands/handlers/__tests__/rename-row.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/internal-rename-row.spec.ts
- src/features/draft/commands/handlers/api-base-row.handler.ts
- src/features/draft/commands/handlers/api-create-row.handler.ts
- src/features/draft/commands/handlers/api-rename-row.handler.ts
- src/features/draft/commands/handlers/api-update-row.handler.ts
- src/features/draft/commands/handlers/index.ts
- src/features/draft/commands/handlers/rename-row.handler.ts
- src/features/draft/commands/handlers/transactional/internal-rename-row.handler.ts
- src/features/draft/commands/impl/api-rename-row.command.ts
- src/features/draft/commands/impl/rename-row.command.ts
- src/features/draft/commands/impl/transactional/internal-rename-row.command.ts
- src/features/draft/commands/impl/transactional/rename-schema.command.ts
- src/schema.gql
> feat: rename row (no refs)

- src/__tests__/utils/prepareBranch.ts
- src/features/draft/commands/handlers/__tests__/transactional/rename-schema.spec.ts
- src/features/draft/commands/handlers/__tests__/utils.ts
- src/features/draft/commands/handlers/remove-table.handler.ts
- src/features/draft/commands/handlers/transactional/rename-schema.handler.ts
- src/features/share/utils/schema/lib/getForeignKeyPatchesFromSchema.ts
- src/features/share/utils/schema/lib/getForeignKeyPathcesFromSchema.spec.ts
> feat: rename table and foreign key

- src/__tests__/utils/schema/schema.mocks.ts
- src/features/draft/commands/handlers/__tests__/rename-row.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/internal-rename-row.spec.ts
- src/features/draft/commands/handlers/transactional/internal-rename-row.handler.ts
- src/features/draft/commands/impl/transactional/internal-rename-row.command.ts
- src/features/share/utils/schema/lib/getForeignKeysFromValue.ts
- src/features/share/utils/schema/lib/replaceForeignKeyValue.spec.ts
- src/features/share/utils/schema/lib/replaceForeignKeyValue.ts
> feat: rename row and refs

- src/__tests__/utils/prepareProject.ts
- src/features/auth/commands/handlers/create-user.handler.ts
- src/features/branch/commands/handlers/create-branch-by-revision-id.handler.ts
- src/features/draft/commands/handlers/__tests__/create-row.spec.ts
- src/features/draft/commands/handlers/__tests__/create-table.handler.spec.ts
- src/features/draft/commands/handlers/__tests__/rename-row.spec.ts
- src/features/draft/commands/handlers/__tests__/rename-table.spec.ts
- src/features/draft/commands/handlers/create-row.handler.ts
- src/features/draft/commands/handlers/create-table.handler.ts
- src/features/draft/commands/handlers/rename-row.handler.ts
- src/features/draft/commands/handlers/rename-table.handler.ts
- src/features/project/commands/handlers/create-project.handler.ts
- src/features/share/utils/validateUrlLikeId/validateUrlLikeId.spec.ts
- src/features/share/utils/validateUrlLikeId/validateUrlLikeId.ts
> feat: naming constraints

- package-lock.json
- package.json
- src/features/draft/commands/handlers/__tests__/create-row.spec.ts
- src/features/draft/commands/handlers/__tests__/rename-row.spec.ts
- src/features/draft/commands/handlers/create-row.handler.ts
- src/features/draft/commands/handlers/rename-row.handler.ts
- src/features/share/utils/validateUrlLikeId/validateRowId.spec.ts
- src/features/share/utils/validateUrlLikeId/validateRowId.ts
> feat validateRowId

- src/features/draft/commands/handlers/__tests__/create-table.handler.spec.ts
- src/features/draft/commands/handlers/__tests__/rename-table.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/internal-rename-row.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/internal-update-row.spec.ts
- src/features/draft/commands/handlers/transactional/get-or-create-draft-table.handler.ts
- src/features/revision/queries/commands/get-tables-by-revision-id.handler.ts
- src/features/share/queries/handlers/transactional/find-table-in-revision-or-throw.handler.ts
- src/features/share/queries/types/find-table-in-revision.types.ts
- src/features/table/queries/handlers/get-tables.handler.ts
> feat: created at updated at in table / default order by 

- src/features/draft/commands/handlers/__tests__/transactional/create-schema.spec.ts
- src/features/draft/commands/handlers/__tests__/transactional/update-schema.spec.ts
- src/features/draft/commands/handlers/__tests__/utils.ts
- src/features/draft/commands/handlers/transactional/create-schema.handler.ts
- src/features/draft/commands/handlers/transactional/update-schema.handler.ts
- src/features/draft/json-schema-validator.service.ts
- src/features/share/utils/schema/lib/getInvalidFieldNamesInSchema.spec.ts
- src/features/share/utils/schema/lib/getInvalidFieldNamesInSchema.ts
- src/features/share/utils/validateUrlLikeId/validateJsonFieldName.spec.ts
- src/features/share/utils/validateUrlLikeId/validateJsonFieldName.ts
- src/features/share/utils/validateUrlLikeId/validateUrlLikeId.ts
> feat: schema fields validation

- src/__tests__/utils/schema/schema.mocks.ts
- src/features/share/utils/schema/lib/createJsonSchemaStore.spec.ts
- src/features/share/utils/schema/lib/createJsonSchemaStore.ts
- src/features/share/utils/schema/model/schema/json-array.store.spec.ts
- src/features/share/utils/schema/model/schema/json-array.store.ts
- src/features/share/utils/schema/model/schema/json-boolean.store.spec.ts
- src/features/share/utils/schema/model/schema/json-boolean.store.ts
- src/features/share/utils/schema/model/schema/json-number.store.spec.ts
- src/features/share/utils/schema/model/schema/json-number.store.ts
- src/features/share/utils/schema/model/schema/json-object.store.spec.ts
- src/features/share/utils/schema/model/schema/json-object.store.ts
- src/features/share/utils/schema/model/schema/json-string.store.spec.ts
- src/features/share/utils/schema/model/schema/json-string.store.ts
- src/features/share/utils/schema/types/schema.types.ts
> add JsonRefSchema

- package-lock.json
- package.json
> chore: s3 deps

- prisma/migrations/20250503143422_/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- src/__tests__/utils/prepareProject.ts
- src/features/auth/commands/handlers/create-user.handler.ts
- src/features/project/commands/handlers/__tests__/utils.ts
- src/features/share/__tests__/diff.service.spec.ts
- src/features/user/commands/handlers/__tests__/set-username.spec.ts
- src/features/user/commands/handlers/set-username.handler.ts
- src/features/user/queries/handlers/__tests__/get-projects-by-user-id.spec.ts
- src/features/user/queries/handlers/__tests__/get-user-organization.spec.ts
> feat: organization.createdId

- src/__tests__/utils/queryTest.ts
- src/api/graphql-api/graphql-api.module.ts
- src/api/rest-api/__tests__/row/upload-file.spec.ts
- src/api/rest-api/__tests__/table/table.spec.ts
- src/core/core.module.ts
- src/main.ts
> refactor: routes

- sonar-project.properties
- src/__tests__/utils/schema/schema.mocks.ts
- src/features/share/json-schema-validator.service.ts
- src/features/share/schema/history-patches-schema.spec.ts
- src/features/share/schema/json-patch-schema.spec.ts
- src/features/share/schema/meta-schema.spec.ts
- src/features/share/schema/meta-schema.ts
- src/features/share/utils/schema/lib/applyPatches.spec.ts
- src/features/share/utils/schema/lib/createJsonSchemaStore.spec.ts
- src/features/share/utils/schema/lib/createJsonSchemaStore.ts
- src/features/share/utils/schema/model/schema/json-array.store.spec.ts
- src/features/share/utils/schema/model/schema/json-array.store.ts
- src/features/share/utils/schema/model/schema/json-boolean.store.spec.ts
- src/features/share/utils/schema/model/schema/json-boolean.store.ts
- src/features/share/utils/schema/model/schema/json-number.store.spec.ts
- src/features/share/utils/schema/model/schema/json-number.store.ts
- src/features/share/utils/schema/model/schema/json-object.store.spec.ts
- src/features/share/utils/schema/model/schema/json-object.store.ts
- src/features/share/utils/schema/model/schema/json-string.store.spec.ts
- src/features/share/utils/schema/model/schema/json-string.store.ts
- src/features/share/utils/schema/types/schema.types.ts
- deprecated / title / description
- enum / contentMediaType / format / pattern for string type
> feat: update meta schema

- src/__tests__/utils/prepareProject.ts
- src/api/rest-api/__tests__/table/get-rows.spec.ts
- src/api/rest-api/share/model/order-by.model.ts
- src/api/rest-api/share/utils/mapToPrismaOrderBy.ts
- src/api/rest-api/share/validators/is-unique-order-by-fields.validator.ts
- src/api/rest-api/table/dto/__tests__/get-table-rows.dto.spec.ts
- src/api/rest-api/table/dto/get-table-rows.dto.ts
- src/api/rest-api/table/table-by-id.controller.ts
- src/features/table/queries/handlers/__tests__/get-rows-by-table.spec.ts
- src/features/table/queries/handlers/get-rows-by-table.handler.ts
- src/features/table/queries/impl/get-rows-by-table.query.ts
- src/main.ts
> Add support for sorting data

- package-lock.json
- package.json
https://github.com/nestjs/nest/issues/15171
> chore: multer

- src/__tests__/utils/prepareProject.ts
- src/features/draft/commands/handlers/__tests__/utils.ts
- src/features/row/queries/handlers/__tests__/resolve-row-foreign-keys-by.spec.ts
- src/features/row/queries/handlers/__tests__/resolve-row-foreign-keys-to.spec.ts
- src/features/row/queries/handlers/resolve-row-foreign-keys-by.handler.ts
- src/features/row/queries/handlers/resolve-row-foreign-keys-to.handler.ts
> fix: computing rows in foreign resolvers
